import { ObjectId } from 'mongoose';

export type TOfferCar = {
  userId: ObjectId;
  dealerId: ObjectId;
  submitListingCarId: ObjectId;
  carCategory: string;
  mark: string;
  carLicensePlateNumber: string;
  model: string;
  cashPrice: number;
  priceType: string[];
  carCondition: string;
  models: string;
  color: string;
  DrivenKm: number;
  fuel: string[];
  gearType: string[];
  modelsYear: number;
  carImages: string[];
  status: 'accept' | 'reject' | 'pending';
  reRegistrationDeRegistrationView: string;
  signatureAsDealer: string;
  signatureAsOwner: string;
  isAggrade: boolean;
  isMoms: boolean;
  advancedPayment: number;
  isOrderTransport: boolean;
  brandImage: string;
  chassisNumber: string;
};
